#!/bin/bash

export HOME=/root

mkdir -p /etc/ssh
ssh-keygen -A >/dev/null 2>&1

authorized-keys "user"
authorized-keys "admin"

cp /etc/keys/ssh/git_ssh.prv /home/user/.ssh/id_ed25519
chown -R user /home/user/.ssh

exec /usr/sbin/sshd \
	-f /var/service/sshd/sshd_config \
	-D \
	-e \
	-o LogLevel=VERBOSE \
	2>&1
