#!/bin/bash
set -e
source /etc/environment
#TODO add quarantine dir and check PGP keys

script_repo=${SCRIPT_REPO?}
script_dir=/home/user/repos/scripts
script_repo_host=$(echo "${SCRIPT_REPO}" | sed 's/.*@\([a-z0-9-]\+\).*/\1/g')
key_repo=${KEY_REPO?}
key_dir=/home/user/repos/keys
key_repo_host=$(echo "${KEY_REPO}" | sed 's/.*@\([a-z0-9-]\+\).*/\1/g')

echo "$USER"
mkdir -p ~/.ssh
ssh-keyscan "$script_repo_host" > ~/.ssh/known_hosts

[ ! -d "$script_dir" ] \
&& mkdir -p "$script_dir" \
&& git clone "$script_repo" "$script_dir"

git -C "$script_dir" pull origin master
git -C "$script_dir" reset --hard origin/master

[ ! -d "$key_dir" ] \
&& mkdir -p "$key_dir" \
&& git clone "$key_repo" "$key_dir"

git -C "$key_dir" pull origin master
git -C "$key_dir" reset --hard origin/master
